---
- name: Setup Web Server on Ubuntu
  hosts: webservers
  become: true
  
  tasks:
  - name: Update apt cache
    apt:
     update_cache: yes
  - name: Install Apache Web Server
    apt:
       name: apache2
       state: present

  - name: Ensure Apache is running
    service:
        name: apache2
        state: started
        enabled: yes

  - name: Install UFW firewall
    apt:
        name: ufw
        state: present

  - name: Allow SSH and HTTP through the firewall
    ufw:
        rule: allow
        name: "{{ item }}"
    with_items:
        - OpenSSH
        - Apache

  - name: Enable the firewall
    ufw:
         state: enabled
